use_frameworks!

platform :ios, '8.0'

target 'TLTestPods_Example' do
  pod 'TLTestPods', :path => '../'

  target 'TLTestPods_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
